export const INCREMENT = 'INCREMENT';
export const DECREASE = 'DECREASE';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';

export const FETCH_USER_DATA = 'FETCH_USER_DATA';
export const FETCH_USER_COMMENTS = 'FETCH_USER_COMMENTS';